export const africanCountryOptions = [
    { label: "Algeria", value: "DZ" },
    { label: "Angola", value: "AO" },
    { label: "Benin", value: "BJ" },
    { label: "Botswana", value: "BW" },
    { label: "Burkina Faso", value: "BF" },
    { label: "Burundi", value: "BI" },
    { label: "Cabo Verde", value: "CV" },
    { label: "Cameroon", value: "CM" },
    { label: "Central African Republic", value: "CF" },
    { label: "Chad", value: "TD" },
    { label: "Comoros", value: "KM" },
    { label: "Congo (Brazzaville)", value: "CG" },
    { label: "Congo (Kinshasa)", value: "CD" },
    { label: "Djibouti", value: "DJ" },
    { label: "Egypt", value: "EG" },
    { label: "Equatorial Guinea", value: "GQ" },
    { label: "Eritrea", value: "ER" },
    { label: "Eswatini", value: "SZ" },
    { label: "Ethiopia", value: "ET" },
    { label: "Gabon", value: "GA" },
    { label: "Gambia", value: "GM" },
    { label: "Ghana", value: "GH" },
    { label: "Guinea", value: "GN" },
    { label: "Guinea-Bissau", value: "GW" },
    { label: "Ivory Coast", value: "CI" },
    { label: "Kenya", value: "KE" },
    { label: "Lesotho", value: "LS" },
    { label: "Liberia", value: "LR" },
    { label: "Libya", value: "LY" },
    { label: "Madagascar", value: "MG" },
    { label: "Malawi", value: "MW" },
    { label: "Mali", value: "ML" },
    { label: "Mauritania", value: "MR" },
    { label: "Mauritius", value: "MU" },
    { label: "Morocco", value: "MA" },
    { label: "Mozambique", value: "MZ" },
    { label: "Namibia", value: "NA" },
    { label: "Niger", value: "NE" },
    { label: "Nigeria", value: "NG" },
    { label: "Rwanda", value: "RW" },
    { label: "São Tomé and Príncipe", value: "ST" },
    { label: "Senegal", value: "SN" },
    { label: "Seychelles", value: "SC" },
    { label: "Sierra Leone", value: "SL" },
    { label: "Somalia", value: "SO" },
    { label: "South Africa", value: "ZA" },
    { label: "South Sudan", value: "SS" },
    { label: "Sudan", value: "SD" },
    { label: "Tanzania", value: "TZ" },
    { label: "Togo", value: "TG" },
    { label: "Tunisia", value: "TN" },
    { label: "Uganda", value: "UG" },
    { label: "Zambia", value: "ZM" },
    { label: "Zimbabwe", value: "ZW" },
];



export const ghanaRegionOptions = [
    { label: "Ahafo", value: "Ahafo" },
    { label: "Ashanti", value: "Ashanti" },
    { label: "Bono", value: "Bono" },
    { label: "Bono East", value: "Bono East" },
    { label: "Central", value: "Central" },
    { label: "Eastern", value: "Eastern" },
    { label: "Greater Accra", value: "Greater Accra" },
    { label: "North East", value: "North East" },
    { label: "Northern", value: "Northern" },
    { label: "Oti", value: "Oti" },
    { label: "Savannah", value: "Savannah" },
    { label: "Upper East", value: "Upper East" },
    { label: "Upper West", value: "Upper West" },
    { label: "Volta", value: "Volta" },
    { label: "Western", value: "Western" },
    { label: "Western North", value: "Western North" }
];

export const serviceOptions = [
  { value: "Basic Plan", label: "Basic Plan" },
  { value: "Premium Support", label: "Premium Support" },
  { value: "Enterprise Service", label: "Enterprise Service" },
];

export const statusOptions = [
  { value: "Verified", label: "Verified" },
  { value: "Not Verified", label: "Not Verified" },
];


